# configure rules to run pipeline only when manually launched via web (this disables CI)
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
      when: always
    - when: never

variables:
  MY_ARTIFACT_TO_SCAN: struts2-showcase.war
  PACKAGE_PATH: ./target
  REPORT_PATH: RlReport
  RLSECURE_ENCODED_LICENSE: $RL_LIC_KEY
  RLSECURE_SITE_KEY: $RL_SITE_KEY
  RL_VERBOSE: true

include:
  - remote: 'https://raw.githubusercontent.com/reversinglabs/rl-scanner-gitlab-include/main/rl-scanner-gitlab-include.yml'

maven-build:
  stage: build

  # select the most appropriate image for your project
  image: maven:3.8-openjdk-17-slim

  artifacts:
    name: "build_artifact"
    paths:
      - $PACKAGE_PATH/*
      - public
    expire_in: 2 weeks

  script:
    - |
      mvn -B clean package
      ls -l ./target
