# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

# Set build number as desired
name: v2.5.28-$(Rev:r)

steps:
- task: Maven@3
  displayName: 'Build'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx2048m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'


- script: |
    echo 'Build number is $(Build.BuildNumber)'
    echo 'Build ID is $(Build.BuildId)'

- task: rl-scanner-cloud-task@1
  displayName: 'RL scan'
  inputs:
    BUILD_PATH: 'target'
    REPORT_PATH: 'RLreport'
    MY_ARTIFACT_TO_SCAN: 'struts2-showcase.war'
    RLPORTAL_SERVER: 'trial'
    RLPORTAL_ORG: 'Trial'
    RLPORTAL_GROUP: 'ProdMgmt'
    RL_PACKAGE_URL: Apache/Struts2showcaseADOext@v2.5.28-$(Build.BuildId)
    RL_VERBOSE: true 
#    RL_DIFF_WITH: 
  env:
    RLPORTAL_ACCESS_TOKEN: $(rlApiToken)

- publish: $(System.DefaultWorkingDirectory)/RLreport/report.cyclonedx.json
  displayName: 'Publish CycloneDX'
  artifact: 'CycloneDX-SBOM'
  condition: succeededOrFailed()

- publish: $(System.DefaultWorkingDirectory)/RLreport/report.spdx.json
  displayName: 'Publish SPDX'
  artifact: 'SPDX-SBOM'
  condition: succeededOrFailed()

- publish: $(System.DefaultWorkingDirectory)/RLreport/report.rl.json
  displayName: 'Publish RL-json'
  artifact: ReversingLabs-JSONreport
  condition: succeededOrFailed()
