# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
 - name: ARTIFACT2SCAN
   value: struts2-showcase.war
 - name: REPORT_PATH
   value: RLSecure
 - name: RL_PORTAL_SERVER
   value: "trial"
 - name: RL_PORTAL_ORG
   value: "Trial"
 - name: RL_PORTAL_GROUP
   value: "'SSCS Demo'"
 - name: RL_PACKAGE_URL
   value: "Apache/Struts2showcaseADO@v2.5.28"

steps:
- task: Maven@3
  displayName: 'Build'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx2048m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- bash: |
    mkdir -p $(REPORT_PATH)
    docker run --rm -u $(id -u):$(id -g) \
      -e RLPORTAL_ACCESS_TOKEN=$(RLPORTAL_ACCESS_TOKEN) \
      -v $(System.DefaultWorkingDirectory)/target:/packages:ro \
      -v $(System.DefaultWorkingDirectory)/$(REPORT_PATH):/report \
      reversinglabs/rl-scanner-cloud:latest \
        rl-scan \
          --replace \
          --rl-portal-server=$(RL_PORTAL_SERVER) \
          --rl-portal-org=$(RL_PORTAL_ORG) \
          --rl-portal-group=$(RL_PORTAL_GROUP) \
          --purl=$(RL_PACKAGE_URL) \
          --file-path=/packages/$(ARTIFACT2SCAN) \
          --report-path=/report \
          --report-format=all
  displayName: 'RL scan via Docker Cloud Scan image'

- publish: $(System.DefaultWorkingDirectory)/$(REPORT_PATH)/report.cyclonedx.json
  displayName: 'Publish CycloneDX'
  artifact: 'CycloneDX-SBOM'
  condition: succeededOrFailed()

- publish: $(System.DefaultWorkingDirectory)/$(REPORT_PATH)/report.spdx.json
  displayName: 'Publish SPDX'
  artifact: 'SPDX-SBOM'
  condition: succeededOrFailed()

- publish: $(System.DefaultWorkingDirectory)/$(REPORT_PATH)/report.rl.json
  displayName: 'Publish RL-json'
  artifact: ReversingLabs-JSONreport
  condition: succeededOrFailed()
