name: Docker Test

on:
  workflow_dispatch:

jobs:

  Docker-Test:
    runs-on: ubuntu-latest

    steps:
      # Check out repository under $GITHUB_WORKSPACE, so job can access it
      - name: Check out 
        uses: actions/checkout@v3
        
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'maven'
          
      - name: Build
        run: |
          mvn -B clean package
          ls -lt ./target

      - name: Docker test 1
        uses: addnab/docker-run-action@v3
        env: 
          RL_LIC: ${{ secrets.RL_LIC_KEY }}
          RL_SITE: ${{ secrets.RL_SITE_KEY }}        
        with:
            image: alpine:latest
            options: -v ${{ github.workspace }}:/var/www -e ABC=123
            run: |
              pwd
              echo $ABC

      - name: Docker test 2
        uses: addnab/docker-run-action@v3
        with:
            image: python:3.11-alpine3.17
            options: -v ${{ github.workspace }}:/var/www -e ABC=456
            run: |
              pwd
              python --version
              echo $ABC
