name: RL Scan with rl-scanner-only action

on:
  workflow_dispatch:

env:
  REPORT_DIR: "RLreport"

jobs:
  Build-And-Scan:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3.5.3

      - name: Set Current Date Time
        run: |
          echo "DT_NOW=$(date +%Y%m%d-%H%M%S)" >> ${GITHUB_ENV}

      - name: Set up Java
        uses: actions/setup-java@v3.11.0
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'maven'

      - name: Build
        run: |
          mvn -B clean package

      - name: RL scan
        continue-on-error: true # Set to false if you want the overall run to fail when the scan detects policy violations
        id: scan

        env:
          RLSECURE_ENCODED_LICENSE: ${{ secrets.RL_LIC_KEY }}
          RLSECURE_SITE_KEY: ${{ secrets.RL_SITE_KEY }}

        uses: reversinglabs/gh-action-rl-scanner-only@v1
        with:
          artifact-to-scan: 'target/struts2-showcase.war'
          report-path: ${{ env.REPORT_DIR }}

      - name: Archive Report
        if: success() || failure()
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ReversingLabs-report-${{ env.DT_NOW }}
          path: ${{ env.REPORT_DIR }}
