name: RrversingLabs scan

on:
  workflow_dispatch:

jobs:

  RL_Scan:
    runs-on: ubuntu-latest

    steps:
      # Check out repository under $GITHUB_WORKSPACE, so job can access it
      - name: Check out 
        uses: actions/checkout@v3
        
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'maven'
          
      - name: Build
        run: mvn -B clean package

      - name: RL Scan
        env: 
          RL_LIC: ${{ secrets.RL_LIC_KEY }}
          RL_SITE: ${{ secrets.RL_SITE_KEY }}
        run: ls -lt ./target
        
      #- uses: actions/upload-artifact@v3
      #  with:
      #    name: RLScanResults
      #    path: rl.report.json  
